include:
  - ./docker-compose-services.yml

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: autolycus_api
    container_name: autolycus_api
    environment:
      - API_DEBUG=True
    env_file:
      - ./.env
    volumes:
      - ./api:/app
      - ${DOWNLOADS_PATH:-./volumes/downloads}:/downloads
    restart: always
    depends_on:
      - redis
      - mongodb
    networks:
      - autolycus_network

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    image: autolycus_ui_dev
    container_name: autolycus_ui_dev
    env_file:
      - ./.env
    environment:
      - BUILD_ENV=dev
    volumes:
      - ./ui:/app
    restart: always
    depends_on:
      - api
    networks:
      - autolycus_network
